
import csv

stroke_map = {
        "ch": "CH",
        "df": "DF",
        "ea": "A&'",
        "h": "'",
        "ia": "A&E",
        "jnt": "JNT",
        "ld": "LD",
        "mn": "MN",
        "mt": "MT",
        "ng": "NG",
        "nk": "NK",
        "nt": "NT",
        "sh": "SH",
        "ss": "SS",
        "td": "TD",
        "th": "TH",
        "tm": "TM",
        "tn": "TN",
        "w": "_",
        "ya": "A|",
        "ye": "E|",
        "yi": "I|",
        "a": "A",
        "a1": "A",
        "a2": "A~",
        "e": "E",
        "e1": "E",
        "e2": "E~",
        "i": "I",
        "i1": "I",
        "i2": "I~",
        "s": "S",
        "s1": "S)",
        "s2": "S(",
        "th": "TH",
        "th1": "TH(",
        "th2": "TH)",
        "x": "X",
        "x1": "X)",
        "x2": "X(",
        "/": "^",
        "b": "B",
        "d": "D",
        "f": "F",
        "g": "G",
        "j": "J",
        "k": "K",
        "l": "L",
        "m": "M",
        "n": "N",
        "o": "O",
        "p": "P",
        "r": "R",
        "t": "T",
        "u": "U",
        "v": "V",
        "z": "Z",
}

with open('./anniversary-supplement/anniversary_supplement.csv') as csv_file:
    reader = csv.DictReader(csv_file)
    for row in reader:
        print(row["word"], row["form"])
