
name: Upload Dictionaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish Dictionaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    - name: Make dictionary zip files
      run: make all
    - name: Upload dictionaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file_glob: true
        file: ./*.zip
